FROM docker.io/nvidia/cuda:12.9.1-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y wget gnupg && \
    apt-get install -y --no-install-recommends \
        openmpi-bin openmpi-common libopenmpi-dev vim && \
    # Download Nsight Systems .deb from NVIDIA
    wget https://developer.nvidia.com/downloads/assets/tools/secure/nsight-systems/2025_6/nsight-systems-2025.6.1_2025.6.1.190-1_amd64.deb && \
    apt-get install -y ./nsight-systems-2025.6.1_2025.6.1.190-1_amd64.deb
# 1) Tools + add Mozilla signing key & repo
RUN apt-get update \
  && apt install -y curl gnupg ca-certificates \
  && curl -fsSL https://dl.google.com/linux/linux_signing_key.pub \
 | gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg >/dev/null \
  && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] \
http://dl.google.com/linux/chrome/deb/ stable main" \
 | tee /etc/apt/sources.list.d/google-chrome.list


# 3) Install the real .deb Firefox from Mozilla’s repo
#    (Optional: add runtime deps commonly needed#    (Optional: add runtime deps commonly needed in containers)
RUN apt-get update \
 && apt-get install -y google-chrome-stable glmark2 \
      dbus-x11 libcanberra-gtk3-module libasound2 fonts-liberation

RUN apt-get update \
  && apt-get install -y software-properties-common \
  && apt-get install -y nvidia-cuda-toolkit \
  && add-apt-repository -y universe \
  && apt-get update \
  && apt-get install -y libpulse0 pulseaudio-utils \
  && rm -rf /var/lib/apt/lists/*

